GET http://localhost:9080/register


###

POST http://localhost:9080/register
Content-Type: "application/json"


{
  "email": "kg12345@gmail.com",
  "password": "new",
  "age":22,
  "name":"test"
}

###

POST http://localhost:9080/account/login
Content-Type: application/json


{
  "name":"kushan"
}
